const data = {
"dach raum": [
    { name: "Germany", code: "de", drive: "r", fakten: ["heimvorteil", "nicht irene riek"], bilder: ["https://de.plonkit.net/images/germany/800px-Karte_Telefonvorwahlen_Deutschland.png", "https://de.plonkit.net/images/germany/postleitzahlen_deutschland_cropped.png", "https://de.plonkit.net/images/resize/450/80/germany/German_flags.jpg", "https://de.plonkit.net/images/resize/450/80/germany/German_Suffixes_Map.png"] },
    { name: "Austria", code: "at", drive: "r", fakten: ["Round wooden poles", "ortseingang und richtungs sign haben blaue border"], bilder: ["https://de.plonkit.net/images/resize/450/80/austria/Austria_or_Slovenia.png", "https://de.plonkit.net/images/resize/450/80/austria/Pedestrian_sign.png"] },
    { name: "Switzerland", code: "ch", drive: "r", fakten: ["low-cam"], bilder: ["https://de.plonkit.net/images/resize/450/80/switzerland/2_digit_postcode_switzerland.png", "https://de.plonkit.net/images/resize/450/80/switzerland/Switzerland_License_Plate.png", "https://de.plonkit.net/images/resize/450/80/switzerland/ch_pedestrian_sign.png"] },
    { name: "Liechtenstein", code: "li", drive: "r", fakten: ["Busstop Hellgrün und weiß mit LIEMOBIL", "road signs mit metal border"], bilder: ["https://de.plonkit.net/images/resize/450/80/liechtenstein/Liechtenstein_plates.png", "https://de.plonkit.net/images/resize/450/80/liechtenstein/2.png", "https://de.plonkit.net/images/resize/450/80/liechtenstein/6.png"] },
],
"flach region": [
    { name: "Belgium", code: "be", drive: "r", fakten: ["red brick house north/west", "gray brick house south (FR)"], bilder: ["https://de.plonkit.net/images/resize/450/80/belgium/Belgium_License_Plate.png", "https://de.plonkit.net/images/resize/450/80/belgium/Belgium_Bollards.png"] },
    { name: "Luxembourg", code: "lu", drive: "r", fakten: ["gelbe eu plate", "Chevrons are black with yellow arrows", "french pole", "signposts blue and white"], bilder: ["https://de.plonkit.net/images/resize/450/80/luxembourg/Bollards.png"] },
    { name: "Netherlands", code: "nl", drive: "r", fakten: ["yellow licence plates", "keine utility poles nur die fetten power lines", "flat as hell", "ländliche Straßen sind von Baumreihen gesäumt"], bilder: ["https://de.plonkit.net/images/resize/600/80/netherlands/Area_codes_of_the_Netherlands.png", "https://de.plonkit.net/images/resize/450/80/netherlands/Dutch_bollard.png", "https://de.plonkit.net/images/resize/450/80/netherlands/Pole_markings.png", "https://de.plonkit.net/images/resize/450/80/netherlands/Windmills.png"] },		
    { name: "France", code: "fr", drive: "r", fakten: ["ladder or waffle poles", "french poles"], bilder: ["https://de.plonkit.net/images/resize/450/80/france/1_licenceplate2.png", "https://de.plonkit.net/images/resize/450/80/france/Bollard.png", "https://external-preview.redd.it/french-regional-numbering-plan-region-guessing-v0-FOSxTOBMgYXnQNG6mkMLxMwAfDYtw412MdTscCtLqk8.png?auto=webp&s=c30ca3cc8bc9c06a6584ae7e719cc9b35be47f04", "https://de.plonkit.net/images/resize/450/80/france/2_postcodes.png"] },
],
"urlaub region": [
    { name: "Portugal", code: "pt", drive: "r", fakten: ["eu plate gelb rechts 100% portugal", "Ç Ã Õ Â Ê", "NO Ñ", "Eucalyptus trees (!nordspanien)", "straße = Rua OHNE AKZENT AUF DEM U"], bilder: ["https://de.plonkit.net/images/resize/450/80/portugal/2areacodes_darkmode.webp", "https://de.plonkit.net/images/resize/450/80/portugal/eucalyptus.png"] },
    { name: "Spain", code: "es", drive: "r", fakten: ["pedestrian crossing signs have 8 stripes", "stop signs have a distinct small font", "straße = calle"], bilder: ["https://de.plonkit.net/images/resize/600/80/spain/Spain-telephone-codes__281_29_darkmode.png", "https://de.plonkit.net/images/resize/450/80/spain/Spain-road-codes-small-version-v2_darkmode.png","https://de.plonkit.net/images/resize/450/80/spain/Spain_stop_sign.png"] },
    { name: "Italy", code: "it", drive: "r", fakten: ["front short plate", "3 eck bollards", "straße = via", "areacodes werden größer richtung osten dann süden"], bilder: ["https://de.plonkit.net/images/resize/450/80/italy/it_licenceplate.png", "https://de.plonkit.net/images/resize/450/80/italy/it_phonecodes.png"] },
    { name: "Andorra", code: "ad", drive: "r", fakten: ["andorra stone buildings", "nur gen2/gen3 coverage", "gen3 hat medium-short antenna"], bilder: ["https://de.plonkit.net/images/resize/450/80/andorra/Andorra_License_Plate.png"] },
],
"norden": [
    { name: "Finland", code: "fi", drive: "r", fakten: ["short plate", "most Finnish street names end in “tie” or “katu”", "nur ä und ö", "viele Doppelvokale"], bilder: ["https://de.plonkit.net/images/resize/450/80/finland/Blue_and_white_signposts.png", "https://de.plonkit.net/images/resize/450/80/finland/Finland_yellow_sign_background.png"] },
    { name: "Norway", code: "no", drive: "r", fakten: ["'Sone' mit speed limit -> 30er zone", "Straße = formen von vei und gata", "traffic signs red outline and white background !! fin swe gelber background !!"], bilder: ["https://de.plonkit.net/images/resize/450/80/norway/no_roadnumbers_darkmode.webp", "https://de.plonkit.net/images/resize/450/80/norway/no_licenceplate.png", "https://de.plonkit.net/images/resize/450/80/norway/no_roadlines.png", "https://de.plonkit.net/images/resize/450/80/norway/no_bollard.png"] },
    { name: "Sweden", code: "se", drive: "r", fakten: ["taxi plate gelb", "Å", "anomaly"], bilder: ["https://de.plonkit.net/images/resize/450/80/sweden/busstopp3.png", "https://de.plonkit.net/images/resize/450/80/sweden/herrg_C3_A5rman.png", "https://de.plonkit.net/images/resize/450/80/sweden/chevron.png", "https://de.plonkit.net/images/resize/450/80/sweden/vagskyltar.png"] },
    { name: "Denmark", code: "dk", drive: "r", fakten: ["flat", "white double middle lines", "Æ, Ø, and Å", "red brick houses"], bilder: ["https://de.plonkit.net/images/resize/450/80/denmark/Denmark_License_Plate.png", "https://de.plonkit.net/images/resize/450/80/denmark/Signpost.png"] },
],
"cup of tea": [
    { name: "United Kingdom", code: "gb", drive: "l", fakten: ["red brick house", "timber farm house"], bilder: ["https://de.plonkit.net/images/resize/450/80/united-kingdom/gb_phone_numbers.webp","https://de.plonkit.net/images/resize/450/80/united-kingdom/United_Kingdom_License_Plate.png", "https://de.plonkit.net/images/resize/450/80/united-kingdom/Cats_eyes_dashes2.png"] },
    { name: "Ireland", code: "ie", drive: "l", fakten: ["only white eu plate no yellow", "yellow outside dashes !! NZ !!", "black roofs", "Vorfahrt achten: yield NICHT GIVE WAY"], bilder: ["https://de.plonkit.net/images/resize/450/80/ireland/Ireland-road-numbers2.png", "https://de.plonkit.net/images/resize/450/80/ireland/ie_phonecodes.png"] },
    { name: "Iceland", code: "is", drive: "r", fakten: ["karg und baumlos", "vulkanisch", "unique letters: ð þ Ð æ", "road nummern im kreis"], bilder: ["https://de.plonkit.net/images/resize/600/80/iceland/Iceland-road-numbering-map.png", "https://de.plonkit.net/images/resize/450/80/iceland/Iceland_Bollard.jpg","https://de.plonkit.net/images/resize/600/80/iceland/iceland_Coverage_Map.png"] },
],
"kleine länder": [
    { name: "San Marino", code: "sm", drive: "r", fakten: ["painted blue crosswalks and hanging signs"], bilder: ["https://de.plonkit.net/images/resize/450/80/san-marino/San_Marino_License_Plate.png", "https://de.plonkit.net/images/resize/450/80/san-marino/San_Marino_Chevron.png"] },  
    { name: "North Macedonia", code: "mk", drive: "r", fakten: ["gen3 no antenna", "unique to Macedonian: Ѓ Ќ", "Serbian and Macedonian: Љ Њ Џ"], bilder: ["https://de.plonkit.net/images/resize/450/80/north-macedonia/North_Macedonia_License_Plate.png", "https://de.plonkit.net/images/resize/450/80/north-macedonia/Greek-Lamp-FYROM.png"] },
	{ name: "Montenegro", code: "me", drive: "r", fakten: ["Guardrails rusted", "sky rifts"], bilder: ["https://de.plonkit.net/images/resize/450/80/montenegro/Montenegro_Licence_Plate.png", "https://de.plonkit.net/images/resize/450/80/montenegro/Bollard.png", "https://de.plonkit.net/images/resize/450/80/montenegro/me_coverage.png"] },
],
"törken": [
    { name: "Turkey", code: "tr", drive: "r", fakten: ["törkische onkel meta"], bilder: ["https://de.plonkit.net/images/resize/450/80/turkey/tr_language.png", "https://de.plonkit.net/images/resize/450/80/turkey/tr_dur.png", "https://de.plonkit.net/images/resize/600/80/turkey/tr_areacodes_nobg.png"] },
    { name: "Albania", code: "al", drive: "r", fakten: ["+355", "black google car", "double eu oder rot eu plates", "Viele Wörter mit sh, rr, ë", "Rruga = Straße"], bilder: ["https://de.plonkit.net/images/resize/600/80/albania/Bollards.png", "https://de.plonkit.net/images/albania/albania_plate.png", "https://de.plonkit.net/images/resize/450/80/albania/Albanian.png"] },
    { name: "Croatia", code: "hr", drive: "r", fakten: ["pedestrian sign with belt and 5 stripes"], bilder: ["https://de.plonkit.net/images/resize/450/80/croatia/Croatia_License_Plate.png", "https://de.plonkit.net/images/resize/450/80/croatia/hr_areacodes_copy.png"] },
    { name: "Greece", code: "gr", drive: "r", fakten: ["kreta= antenne mit nem bulge"], bilder: ["https://de.plonkit.net/images/resize/450/80/greece/gr_language.png", "https://de.plonkit.net/images/resize/600/80/greece/gr_areacodes_darkmode.png", "https://de.plonkit.net/images/resize/450/80/greece/gr_poletop.png", "https://de.plonkit.net/images/resize/450/80/greece/gr_licenceplate.png"] },
],
"s-osten": [
    { name: "Serbia", code: "rs", drive: "r", fakten: ["Č Ć Đ Š Ž Љ љ Њ њ Џ џ", "unique: Ђ ђ Ћ ћ", "oben 2er dann 1er unten links 3er", "vorwahl 381"], bilder: ["https://de.plonkit.net/images/resize/450/80/serbia/area_codes_colourized.png", "https://de.plonkit.net/images/resize/450/80/serbia/Serbia_Plate.png", "https://de.plonkit.net/images/resize/450/80/serbia/Serbia_Coverage_Map_.png"] },
    { name: "Slovakia", code: "sk", drive: "r", fakten: ["Ľ Ô Ä Ŕ Ĺ", "diamond shaped dach tiles", "10 digit phonenumber", "Czech phonenumbers generally do not begin with a 0"], bilder: ["https://de.plonkit.net/images/resize/450/80/slovakia/sk_areacodes.png", "https://de.plonkit.net/images/resize/450/80/slovakia/sk_bollard.png", "https://de.plonkit.net/images/resize/450/80/slovakia/sk_lampbase.png"] },
    { name: "Slovenia", code: "si", drive: "r", fakten: ["ČŠŽ"], bilder: ["https://de.plonkit.net/images/resize/450/80/slovenia/si_bollard.png", "https://de.plonkit.net/images/resize/450/80/slovenia/slovenia_roadlines.png"] },

],
"osten": [
    { name: "Czechia", code: "cz", drive: "r", fakten: ["Czech uses Ř, Ě and Ů", "thin white border, which is separated from the edge by a second coloured border"], bilder: ["https://de.plonkit.net/images/resize/450/80/czechia/cz_bollard.png", "https://de.plonkit.net/images/resize/450/80/czechia/cz_streetsigns.png"] },
    { name: "Poland", code: "pl", drive: "r", fakten: ["white double middle lines", "nur polen: Ł", "roads lined by rows of trees"], bilder: ["https://de.plonkit.net/images/resize/450/80/poland/Poland-bollard.png", "https://de.plonkit.net/images/resize/450/80/poland/Poland_Suffix_Map.png", "https://de.plonkit.net/images/resize/450/80/poland/Poland-area-codes.png", "https://de.plonkit.net/images/resize/450/80/poland/Poland-yellow-sign2.png"] },
    { name: "Romania", code: "ro", drive: "r", fakten: ["vorfahrt achten mega fette rote line mit mini white outline", "pastelfarbene häuser"], bilder: ["https://de.plonkit.net/images/resize/450/80/romania/ro_polesticker.png", "https://de.plonkit.net/images/resize/450/80/romania/ro_directionalsigns.png", "https://de.plonkit.net/images/resize/450/80/romania/ro_language.png", "https://de.plonkit.net/images/resize/450/80/romania/ro_holeypole.png"] },
    { name: "Hungary", code: "hu", drive: "r", fakten: ["taxi plates sind gelb", "grey flag on the antenna in gen3", "8 stellige tel. = 3 & 4 stelle ist areacode", "10 stellige tel. = erste 2 zahlen areacode", "2. stelle 0 oder 1 = nicht brauchbare nummer", "Budapest = 1 oder 3 stelle ist ne 1"], bilder: ["https://de.plonkit.net/images/resize/800/80/hungary/hu_areacodes.png", "https://de.plonkit.net/images/resize/450/80/hungary/hu_language.png", "https://de.plonkit.net/images/resize/450/80/hungary/hu_pedestriansign.png", "https://de.plonkit.net/images/resize/600/80/hungary/hu_roadnumbers.png"] },
],
"krieg": [
    { name: "Ukraine", code: "ua", drive: "r", fakten: ["Є Ґ Ї"], bilder: ["https://de.plonkit.net/images/resize/450/80/ukraine/Ukraine_License_Plate.png", "https://de.plonkit.net/images/resize/450/80/ukraine/Area_codes.png"] },
    { name: "Russia", code: "ru", drive: "r", fakten: ["white plate", "Ы Э Ё Ъ", "street is улица (ulitsa), kurz ул", "word for city is город (gorod), abbreviated г. (g.)", "Sibirische Lärchen = osten"], bilder: ["russia.png", "https://de.plonkit.net/images/resize/450/80/russia/pedestriansign.png", "https://de.plonkit.net/images/resize/600/80/russia/siberianlarches.png"] },
    { name: "Bulgaria", code: "bg", drive: "r", fakten: ["letter “Ъ” is only found in Bulgarian and Russian", "street is улица (ulitsa), kurz ул", "pedestrian signs have four stripes, and the person is wearing a hat"], bilder: ["https://de.plonkit.net/images/resize/450/80/bulgaria/Exquisite_bulgarian_masonry.png"] },
],
"baltic": [
    { name: "Estonia", code: "ee", drive: "r", fakten: ["signs have a thin red border, with no white outline ", "blue and white signpost wrappings", "Finnic languages"], bilder: ["https://de.plonkit.net/images/resize/450/80/estonia/Estonian_Signs.png", "https://de.plonkit.net/images/resize/450/80/estonia/Concrete_pole.png"] },
    { name: "Latvia", code: "lv", drive: "r", fakten: ["dünne bollards", "signs have a thick red border, with a thin white outline around it", "von baltic das einzige mit 5 stripe pedestrian signs lange beine", "in baltic unique letters: Ā Ē Ī Ģ Ķ Ļ Ņ"], bilder: ["https://de.plonkit.net/images/resize/450/80/latvia/Bollard.png", "https://de.plonkit.net/images/resize/450/80/latvia/Latvian_Signs.png"] },
    { name: "Lithuania", code: "lt", drive: "r", fakten: ["signs have a relatively thin red border, with a thin white outline", "in baltic unique letters: Ą Ę Į Ų Ė with a single dot", "straße = gatve oder g."], bilder: ["https://de.plonkit.net/images/resize/450/80/lithuania/Lithuanian_Signs.png", "https://de.plonkit.net/images/resize/450/80/lithuania/Pedestrian_sign_Lithuania.png", "https://de.plonkit.net/images/resize/450/80/lithuania/lithuania_state_flag.png"] },
],




"arab":[
    { name: "Oman", code: "om", drive: "r", fakten: ["white truck", "desert auch ohne straße", "Black-and-yellow curbs"], bilder: ["https://de.plonkit.net/images/resize/450/80/oman/13.png", "https://de.plonkit.net/images/resize/450/80/oman/3.png", "https://de.plonkit.net/images/resize/450/80/oman/10.png"] },
    { name: "United Arab Emirates", code: "ae", drive: "r", fakten: ["unique: white car with visible black roof racks in gen 3", "Reddish stones on sidewalk", "Divided roads and roundabouts "], bilder: ["https://de.plonkit.net/images/resize/450/80/united-arab-emirates/ae_roadlines.png"] },
    { name: "Qatar", code: "qa", drive: "r", fakten: ["white on red and white on blue chevrons"], bilder: ["https://de.plonkit.net/images/resize/450/80/qatar/Qatar_License_Plate.png", "https://de.plonkit.net/images/resize/450/80/qatar/Qatarpoles.png", "https://de.plonkit.net/images/resize/450/80/qatar/Crossing_Sign.png"] },
    { name: "Jordan", code: "jo", drive: "r", fakten: ["no english writing", "chevrons are white with red arrows"], bilder: ["https://de.plonkit.net/images/resize/450/80/jordan/Jordan_License_Plate.png", "https://de.plonkit.net/images/resize/600/80/jordan/jo_coverage.png", "https://de.plonkit.net/images/resize/450/80/jordan/Jordan_road.png", "https://de.plonkit.net/images/resize/450/80/jordan/jo_architecture.png"] },
	{ name: "Israel", code: "il", drive: "r", fakten: ["Chevrons are white on black"], bilder: ["https://de.plonkit.net/images/resize/450/80/israel-west-bank/il_Licence_Plate.png", "https://de.plonkit.net/images/resize/450/80/israel-west-bank/il_language.png", "https://de.plonkit.net/images/resize/450/80/israel-west-bank/il_stopsign.png", "https://de.plonkit.net/images/resize/450/80/israel-west-bank/IL_Stripy_Pole.png"] },
    { name: "Lebanon", code: "lb", drive: "r", fakten: ["arabisch + english oder french", "unique shitcam in middle east"], bilder: ["https://de.plonkit.net/images/resize/450/80/lebanon/lb_licenceplates.png", "https://de.plonkit.net/images/resize/450/80/lebanon/Lebanon_Poles.png", "https://de.plonkit.net/images/resize/450/80/lebanon/Lebanon_Coverage_Map.png"] },
],

"asien russland":[
    { name: "Mongolia", code: "mn", drive: "r", fakten: ["ЗОГС stop sign.", "unique: Ɵ Ү", "double vowels aa ƟƟ ЭЭ are common", "truck mit tent"], bilder: ["https://de.plonkit.net/images/resize/450/80/mongolia/1._licenceplate.jpeg", "https://de.plonkit.net/images/resize/450/80/mongolia/1._bollard.png"] },
    { name: "Kyrgyzstan", code: "kg", drive: "r", fakten: ["watch car and driving richtung"], bilder: ["https://de.plonkit.net/images/resize/450/80/kyrgyzstan/Please_dont_guess_Guatemala.png", "https://de.plonkit.net/images/resize/600/80/kyrgyzstan/Kyrgyzstan_Driving_Directions_V2.png", "https://de.plonkit.net/images/resize/450/80/kyrgyzstan/Kyrgyzstan_License_Plate.png"] },
],

"china schrift":[
    { name: "Japan", code: "jp", drive: "l", fakten: ["linksverkehr", "low cam", "NEVER outside yellow lines"], bilder: ["https://de.plonkit.net/images/resize/450/80/japan/2.png", "https://de.plonkit.net/images/resize/450/80/japan/9.png", "https://de.plonkit.net/images/resize/450/80/japan/13.png", "https://de.plonkit.net/images/resize/600/80/japan/jp_areacodes_darkmode.png", "https://de.plonkit.net/images/resize/600/80/japan/37.png"] },
    { name: "China", code: "cn", drive: "r", fakten: ["tripod coverage", "motion blur"], bilder: ["https://de.plonkit.net/images/resize/450/80/china/cn_licenceplate.png", "https://de.plonkit.net/images/resize/600/80/china/cn_coverage.png"] },
    { name: "Taiwan", code: "tw", drive: "r", fakten: ["japan aber rechtsverkehr", "rechtsverkehr"], bilder: ["https://de.plonkit.net/images/resize/600/80/taiwan/a-more-detailed-taiwan-area-code-map.webp", "https://de.plonkit.net/images/resize/450/80/taiwan/ui_remover.png", "https://de.plonkit.net/images/resize/600/80/taiwan/ui_remover__281_29.png", "https://de.plonkit.net/images/resize/600/80/taiwan/Traditional_Chinese.png"] },
    { name: "South Korea", code: "kr", drive: "r", fakten: ["autumn and winter", "right driving"], bilder: ["https://de.plonkit.net/images/resize/600/80/south-korea/licen_plae.png", "https://de.plonkit.net/images/resize/600/80/south-korea/kr_script.png", "https://de.plonkit.net/images/resize/600/80/south-korea/kr_pole_marking.png"] },
],

"India type beat":[
    { name: "India", code: "in", drive: "l", fakten: ["left driving"], bilder: ["in_scripts.png", "in_language.png"] },
    { name: "Bangladesh", code: "bd", drive: "l", fakten: ["türkis plate nur bangla"], bilder: ["https://de.plonkit.net/images/resize/450/80/bangladesh/Bangladesh_License_Plate.png", "https://de.plonkit.net/images/resize/450/80/bangladesh/bd_language.png", "https://de.plonkit.net/images/resize/450/80/bangladesh/bollard.png"] },
    { name: "Bhutan", code: "bt", drive: "l", fakten: ["Prayer flags", "thin metal poles"], bilder: ["https://de.plonkit.net/images/resize/450/80/bhutan/Bhutan_License_Plate.png", "https://de.plonkit.net/images/resize/450/80/bhutan/Dzongkha.png", "https://de.plonkit.net/images/resize/450/80/bhutan/stonebarriers.png"] },
    { name: "Sri Lanka", code: "lk", drive: "l", fakten: ["low-cam", "large see-through holes in the LOWER half of the pole"], bilder: ["https://de.plonkit.net/images/resize/450/80/sri-lanka/Sri_Lanka_License_Plate.png","https://de.plonkit.net/images/resize/450/80/sri-lanka/Gen_3_car2.png","https://de.plonkit.net/images/resize/450/80/sri-lanka/Sri_Lanka_scripts.png"] },

],
 
"thai":[
    { name: "Thailand", code: "th", drive: "l", fakten: ["left drive", "yellow middle line", "royal flag = yellow", "phone codes nur haustelefone"], bilder: ["https://de.plonkit.net/images/resize/450/80/thailand/Thailand_License_Plate.png", "https://de.plonkit.net/images/resize/450/80/thailand/th_language.png", "https://de.plonkit.net/images/resize/450/80/thailand/Screenshot%20(638).png", "https://de.plonkit.net/images/resize/450/80/thailand/Indicatifs_Thailande.png"] },
    { name: "Vietnam", code: "vn", drive: "r", fakten: ["right drive", "unique: Road signs have a yellow-orange background"], bilder: ["https://de.plonkit.net/images/resize/450/80/vietnam/vietnam_plate2.png", "https://de.plonkit.net/images/resize/450/80/vietnam/vn_language.png", "https://de.plonkit.net/images/resize/450/80/vietnam/vn_bollard.png", "https://de.plonkit.net/images/resize/450/80/vietnam/vn_directionalsign.png"] },
    { name: "Cambodia", code: "kh", drive: "r", fakten: ["right drive"], bilder: ["https://de.plonkit.net/images/resize/450/80/cambodia/Cambodia_License_Plate.png", "https://de.plonkit.net/images/resize/450/80/cambodia/Khmer.png", "https://de.plonkit.net/images/resize/450/80/cambodia/Cambodia_poles.png", "https://de.plonkit.net/images/resize/450/80/cambodia/House_colours.png"] },
    { name: "Singapore", code: "sg", drive: "l", fakten: ["cleanliness and orderliness", "straßennamen 3 letter codes"], bilder: ["https://de.plonkit.net/images/resize/450/80/singapore/streetsign.png", "https://de.plonkit.net/images/resize/450/80/singapore/Singapore_License_Plate.png", "https://de.plonkit.net/images/resize/450/80/singapore/directionalsign.png", "https://de.plonkit.net/images/resize/450/80/singapore/Untitled_design__2845_29.png"] },
],

"asien insel": [
    { name: "Indonesia", code: "id", drive: "l", fakten: ["3 white sections on plate", "left drive", "outer lines always white", "money is Rupiah (Rp)"], bilder: ["https://de.plonkit.net/images/resize/450/80/indonesia/Indonesia_License_Plate.png", "https://de.plonkit.net/images/resize/450/80/indonesia/Indonesian_language.png", "https://de.plonkit.net/images/resize/450/80/indonesia/Front_License_Plate_on_Motorcycle.png", "https://de.plonkit.net/images/resize/600/80/indonesia/If_you_are_reading_this_have_a_nice_day.png"] },
    { name: "Malaysia", code: "my", drive: "l", fakten: ["2 white sections on plate", "unique: double white center lines", "= indo skript"], bilder: ["https://de.plonkit.net/images/resize/450/80/malaysia/Malaysia_License_Plate.png", "https://de.plonkit.net/images/resize/450/80/malaysia/Untitled_design__2824_29.png", "https://de.plonkit.net/images/resize/450/80/malaysia/Untitled_design__2823_29.png", "https://de.plonkit.net/images/resize/450/80/malaysia/directionalsign.png"] },
    { name: "Philippines", code: "ph", drive: "r", fakten: ["landlines start with 0 followed by area code", "mobile phone numbers start with 09", "rechts drive", "Concrete roads oft", "Octagonal metal poles"], bilder: ["https://de.plonkit.net/images/resize/450/80/philippines/2_areacodes.png", "https://de.plonkit.net/images/resize/450/80/philippines/1_octopole.png", "https://de.plonkit.net/images/resize/450/80/philippines/1_poleinsulator.png", "https://de.plonkit.net/images/resize/450/80/philippines/1_roadline.png"] },
],

"south":[
    { name: "South Africa", code: "za", drive: "l", fakten: ["left drive", "yellow outer lines = not AU", "viel gen2 -> halo-like colour distortion in the sky", "bird poles", "high walls, fences, and gates", "r roads map"], bilder: ["https://de.plonkit.net/images/resize/450/80/south-africa/Bird_poles.png","https://de.plonkit.net/images/resize/450/80/south-africa/Untitled_design21.png", "https://de.plonkit.net/images/resize/600/80/south-africa/ZA-map24.png"] },
    { name: "Botswana", code: "bw", drive: "l", fakten: ["UK-style plates"], bilder: ["https://de.plonkit.net/images/resize/1200/80/botswana/Botswana_Region_Map.png", "https://de.plonkit.net/images/resize/450/80/botswana/Botswana_License_Plate.png", "https://de.plonkit.net/images/resize/450/80/botswana/Botswana_stripeys.png", "https://de.plonkit.net/images/resize/450/80/botswana/Direction_Signs.png"] },
    { name: "Eswatini", code: "sz", drive: "l", fakten: ["green, wooded hills tall golden grass"], bilder: ["https://de.plonkit.net/images/resize/450/80/eswatini/MRroad.png", "https://de.plonkit.net/images/resize/450/80/eswatini/Eswatini_License_Plate.png", "https://de.plonkit.net/images/resize/450/80/eswatini/busshelter.png"] },
    { name: "Lesotho", code: "ls", drive: "l", fakten: ["left drive", "runde buschhütte", "Basotho woollen blanket -> wie so ein mantel"], bilder: ["https://de.plonkit.net/images/resize/450/80/lesotho/Lesotho_License_Plate.png", "https://de.plonkit.net/images/resize/600/80/lesotho/ls_coverage.png"] },
    { name: "Namibia", code: "na", drive: "l", fakten: ["all white truck -> antenna lean slightly to the left", "left drive"], bilder: ["https://de.plonkit.net/images/resize/450/80/namibia/0.png", "https://de.plonkit.net/images/resize/600/80/namibia/10.png", "https://de.plonkit.net/images/resize/600/80/namibia/12.png"] },
],

"ostafrika":[
    { name: "Kenya", code: "ke", drive: "l", fakten: ["grey Toyota SUV following the Street View car", "unique: grüner shop Safaricom", "immer solid white outer - yellow inner solid/dashed"], bilder: ["https://de.plonkit.net/images/resize/450/80/kenya/Kenya_License_Plate.png", "https://de.plonkit.net/images/resize/450/80/kenya/Kenya_Road_Signs.png", "https://de.plonkit.net/images/resize/450/80/kenya/Kenya_Coverage_Map.png", "https://de.plonkit.net/images/resize/450/80/kenya/Safaricom.png"] },
    { name: "Rwanda", code: "rw", drive: "r", fakten: ["camera mount visible", "right drive"], bilder: ["https://de.plonkit.net/images/resize/450/80/rwanda/Rwanda_License_Plate.png", "https://de.plonkit.net/images/resize/450/80/rwanda/RwandanTrio.png", "https://de.plonkit.net/images/resize/600/80/rwanda/Rwanda_Coverge_map.jpg"] },
    { name: "Uganda", code: "ug", drive: "l", fakten: ["left drive", "nur major city coverage -> Kampala"], bilder: ["https://de.plonkit.net/images/resize/450/80/uganda/Uganda_License_Plate.png", "https://de.plonkit.net/images/resize/600/80/uganda/Kampala_Car_3.png"] },
    { name: "Tunisia", code: "tn", drive: "r", fakten: ["follow car", "French and Arabic language"], bilder: ["https://de.plonkit.net/images/resize/450/80/tunisia/tn_coverage.png", "https://de.plonkit.net/images/resize/450/80/tunisia/followcars.png", "https://de.plonkit.net/images/resize/450/80/tunisia/directionalsigns.png", "https://de.plonkit.net/images/resize/450/80/tunisia/round.jpg", "https://de.plonkit.net/images/resize/450/80/tunisia/Tunisia_stop_sign.png", "https://de.plonkit.net/images/resize/450/80/tunisia/Tunisia_License_Plate.png"] },
],

"westafrica": [
    { name: "Ghana", code: "gh", drive: "l", fakten: ["red soil"], bilder: ["https://de.plonkit.net/images/resize/450/80/ghana/Ghana_car.png", "https://de.plonkit.net/images/resize/450/80/ghana/Ghana%20paved%20unpaved%20infographic%202"] },
    { name: "Nigeria", code: "ng", drive: "r", fakten: ["roads ohne lines common", "steile dächer"], bilder: ["https://de.plonkit.net/images/resize/450/80/nigeria/qjpxa6d.png", "https://de.plonkit.net/images/resize/450/80/nigeria/JtDpCOs.png", "https://de.plonkit.net/images/resize/450/80/nigeria/0HpTmNo.png", "https://de.plonkit.net/images/resize/600/80/nigeria/V97CXFq.png"] },
    { name: "Senegal", code: "sn", drive: "r", fakten: ["french"], bilder: ["https://de.plonkit.net/images/resize/450/80/senegal/gen_3.png", "https://de.plonkit.net/images/resize/450/80/senegal/senegal_plates.png", "https://de.plonkit.net/images/resize/600/80/senegal/Senegal_Coverage_Map_v2.png"] },
],

"nord amerika": [
    { name: "Canada", code: "ca", drive: "r", fakten: ["maximum speed sign", "gen 2 (halo sky, big blur) wenig in us", "gen 3 mirror blur bild", "gen 4 low cam", "schilder sind oft weniger wortreich als us"], bilder: ["https://de.plonkit.net/images/resize/600/80/canada/Canadian_KM_markers_map_w_numbers2.png", "https://de.plonkit.net/images/resize/600/80/canada/ca_license_plates_updated.png.png", "https://de.plonkit.net/images/resize/450/80/canada/gen3_blurs.png", "https://de.plonkit.net/images/resize/450/80/canada/Smallcam_NA_.png", "https://de.plonkit.net/images/resize/450/80/canada/Canada_less_wordy_signs.png"] },
    { name: "Mexico", code: "mx", drive: "r", fakten: ["octa pole", "cactus", "place names lot of ‘x’ and ‘tl’ as well as ‘-ec’ and ‘-tlan’ suffixes"], bilder: ["mx_areacodes.png", "https://de.plonkit.net/images/resize/450/80/mexico/mx_bollard.png", "https://de.plonkit.net/images/resize/450/80/mexico/mx_kmmarker.png", "https://de.plonkit.net/images/resize/450/80/mexico/mx_brands.png"] },
    { name: "United States", code: "us", drive: "r", fakten: ["viele wörter an schildern", "speed limit sign"], bilder: ["https://de.plonkit.net/images/resize/450/80/united-states/us_licenceplates_2025.png","https://de.plonkit.net/images/resize/450/80/united-states/us_stateflags_v2.png","https://de.plonkit.net/images/resize/600/80/united-states/2us_speed_limits_darkmode.png","https://de.plonkit.net/images/resize/600/80/united-states/1highway_shields.png", "https://de.plonkit.net/images/resize/450/80/united-states/nopassingzone.png", "https://de.plonkit.net/images/resize/450/80/united-states/rumble_strips.png"] }
],
 
"mitte amerika":[
    { name: "Dominican Republic", code: "do", drive: "r", fakten: ["nur gen3 cov"], bilder: ["https://de.plonkit.net/images/resize/450/80/dominican-republic/googlecar.png", "https://de.plonkit.net/images/resize/450/80/dominican-republic/Dominican_Republic_License_Plate.png", "https://de.plonkit.net/images/resize/450/80/dominican-republic/do_coveragemap.png"] },
    { name: "Panama", code: "pa", drive: "r", fakten: ["hügel", "palmen"], bilder: ["https://de.plonkit.net/images/resize/450/80/panama/2.png", "https://de.plonkit.net/images/resize/450/80/panama/3.png", "https://de.plonkit.net/images/resize/600/80/panama/13.png"] },
    { name: "Guatemala", code: "gt", drive: "r", fakten: ["regenwald"], bilder: ["https://de.plonkit.net/images/resize/450/80/guatemala/gt_licenceplate.png", "https://de.plonkit.net/images/resize/450/80/guatemala/gt_googlecar.png", "https://de.plonkit.net/images/resize/450/80/guatemala/gt_polepaint.png", "https://de.plonkit.net/images/resize/450/80/guatemala/gt_poleplate.png"] },
],  

"south amerika oben": [
    { name: "Bolivia", code: "bo", drive: "r", fakten: ["large red bricks buildings 'unfinished' looks", "cobblestone roads"], bilder: ["https://de.plonkit.net/images/resize/450/80/bolivia/1_licenceplate.png", "https://de.plonkit.net/images/resize/450/80/bolivia/1_googlecar.png", "https://de.plonkit.net/images/resize/450/80/bolivia/1_scuffedpole.png", "https://de.plonkit.net/images/resize/450/80/bolivia/1_wiphala.png", "https://de.plonkit.net/images/resize/450/80/bolivia/2_coveragemap.png"] },
    { name: "Colombia", code: "co", drive: "r", fakten: ["erste zwei zahlen sind die road number, letzte 2 die section"], bilder: ["https://de.plonkit.net/images/resize/450/80/colombia/Colombia_License_Plate.png", "https://de.plonkit.net/images/resize/450/80/colombia/Copy_of_Copy_of_Copy_of_Copy_of_Untitled.png", "https://de.plonkit.net/images/resize/450/80/colombia/kmmarker.png", "https://de.plonkit.net/images/resize/450/80/colombia/Copy_of_Copy_of_Copy_of_Copy_of_Untitled__282_29.png", "https://de.plonkit.net/images/resize/450/80/colombia/co_verage.png"] },
    { name: "Ecuador", code: "ec", drive: "r", fakten: ["unique: short AND long plates in SA"], bilder: ["https://de.plonkit.net/images/resize/450/80/ecuador/Ecuador_License_Plate.png", "https://de.plonkit.net/images/resize/450/80/ecuador/Ecua_poles.png", "https://de.plonkit.net/images/resize/450/80/ecuador/ec_coverage.png"] },
],

"south amerika unten": [
    { name: "Chile", code: "cl", drive: "r", fakten: ["slots on signs"], bilder: ["https://de.plonkit.net/images/resize/450/80/chile/bollard.png", "https://de.plonkit.net/images/resize/450/80/chile/Chile_map_of_K%C3%83%C2%B6ppen_climate_classification_with_new_classification_types_darkmode_wikipediacommons.png", "https://de.plonkit.net/images/resize/450/80/chile/Chile_Road_Naming_System_nobg.png", "https://de.plonkit.net/images/resize/450/80/chile/Chile_Area_Codes.png"] },
    { name: "Peru", code: "pe", drive: "r", fakten: ["gen 4 small cam und normale", "currency Sol s/"], bilder: ["https://de.plonkit.net/images/resize/450/80/peru/1.signpost.png", "https://de.plonkit.net/images/resize/450/80/peru/Peru_poles.png", "https://de.plonkit.net/images/resize/450/80/peru/Peru_Coverage_Map1.png"] },
    { name: "Uruguay", code: "uy", drive: "r", fakten: ["smudgy cam footage"], bilder: ["https://de.plonkit.net/images/resize/450/80/uruguay/Uruguay_License_Plate.png", "https://de.plonkit.net/images/resize/450/80/uruguay/Triple_road_lines.png", "https://de.plonkit.net/images/resize/450/80/uruguay/Bollards_and_barriers.png", "https://de.plonkit.net/images/resize/450/80/uruguay/Trident_pole.png", "https://de.plonkit.net/images/resize/450/80/uruguay/uy_coverage.png"] },
    { name: "Argentina", code: "ar", drive: "r", fakten: ["gen 4 smallcam"], bilder: ["https://de.plonkit.net/images/resize/450/80/argentina/Argentina_License_Plate.png", "https://de.plonkit.net/images/resize/450/80/argentina/Argentina_concrete_poles.png"] },
    { name: "Brazil", code: "br", drive: "r", fakten: ["portugisisch", "red soil"], bilder: ["https://de.plonkit.net/images/resize/450/80/brazil/Brazil_License_Plate.png", "https://de.plonkit.net/images/resize/450/80/brazil/ladders.png", "https://de.plonkit.net/images/resize/450/80/brazil/br_coverage.png", "https://de.plonkit.net/images/resize/450/80/brazil/Brasil_-_C_C3_B3digos_de__C3_A1rea_DDD.png", "https://de.plonkit.net/images/resize/450/80/brazil/cepcodes.png"] },
    { name: "Paraguay", code: "py", drive: "r", fakten: ["meeeen no meta"], bilder: ["https://i.makeagif.com/media/3-15-2020/16cgbq.gif"] },
],

"oceania": [
    { name: "Australia", code: "au", drive: "l", fakten: ["EUKALYPTUS", "fest nur WHITE ROADLINES"], bilder: ["https://de.plonkit.net/images/resize/450/80/australia/Australian_bollard.png", "https://de.plonkit.net/images/resize/450/80/australia/Untitled_design_11.png", "au_phone.png"] },
    { name: "New Zealand", code: "nz", drive: "l", fakten: ["rote highway", "ferns in forest"], bilder: ["https://de.plonkit.net/images/resize/450/80/new-zealand/NZ_Bollard.png", "https://de.plonkit.net/images/resize/450/80/new-zealand/NZ_poles.png", "https://de.plonkit.net/images/resize/450/80/new-zealand/10jOgSh.png", "https://de.plonkit.net/images/resize/450/80/new-zealand/mbmItmT.jpg", "https://de.plonkit.net/images/resize/450/80/new-zealand/round.png", "https://de.plonkit.net/images/resize/600/80/new-zealand/highway_numbering_darkmode_v2.png", "nz_area_codes_new.png"] }
  ]
};